import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/loan.module.css'

export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <h1 className={styles.title}>
                Start by taking a loan!
            </h1>
          <div>
           <form>
            <label>
              Your Name:
             <input type="text" name="name"/>
            </label>
            <label>
              Amount:
             <input type="text" name="name" />
            </label>
            <label>
              Name:
             <input type="text" name="name" />
            </label>
            <label>
              Name:
             <input type="text" name="name" />
            </label>
           </form>
          </div>

        
        </main>
        </div>
        )
    }