import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/pay.module.css'

export default function Home() {
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
            <h1 className={styles.title}>
                Pay back the existing sum you owe to our firm.
            </h1>

        
        </main>
            
        
        </div>
        )
    }